### ISSUE TITLE
missing map in Dashboard

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2110] opened 2019-03-19 17:15 UTC
on Windows 10, IE 11 the map for mapmodule (brainstorming) is not displayed in dashboard. I can't set a district either, it won't save.

![Bildschirmfoto 2019-03-19 um 18 13 56](https://user-images.githubusercontent.com/35491681/54627103-f180fb80-4a72-11e9-8528-cf48b5ad4308.png)

**Comment by phillimorland** [comment] 2019-04-11 08:32
url: https://meinberlin-dev.liqd.net/dashboard/modules/brainstorming-mit-kartenfunktion-7/area_settings/

**Comment by MagdaN** [comment] 2019-04-11 15:53
@CarolingerSeilchenspringer @phillimorland I could reproduce the problem on browserstack and the dev server. When I tried then to reproduce it with my local machine (to fix the bug) it worked nicely. Maybe the other map fixes already fixed it?

**Comment by MagdaN** [comment] 2019-04-23 12:03
@CarolingerSeilchenspringer @treba123 we can't really figure out what the problem is. Maybe this is a problem of browserstack, has some else with a real ie11 reported this issue as well?

**Comment by MagdaN** [comment] 2019-04-23 14:15
Yeah, @treba123 fixed it. So let's close it!

**Closed by MagdaN** 2019-04-23 14:15 UTC
Labels: Type: Bug
