### ISSUE TITLE
edit description/information doesn't work on dev

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1203] opened 2018-02-14 09:35 UTC
can't edit information in all modules on dev-server

also can't edit description on topicprio/placeprio when adding/editing topic/place 

both chrome and firefox

**Comment by kleingeist** [comment] 2018-02-14 09:43
duplicate of #1202

**Closed by kleingeist** 2018-02-14 09:43 UTC
