### ISSUE TITLE
circle to complete publishing

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1953] opened 2019-02-07 11:04 UTC
on mac safari it looks like this.

<img width="315" alt="bildschirmfoto 2019-02-07 um 12 03 39" src="https://user-images.githubusercontent.com/35491681/52407416-871e8800-2ad0-11e9-82a9-d2ce9b93b615.png">

**Comment by phillimorland** [comment] 2019-02-07 14:12
this is a duplicate of issue #857 so closing
Cannot reproduce on my mac safari

**Closed by phillimorland** 2019-02-07 14:12 UTC
