### ISSUE TITLE
Error 413 after picuture upload in projects

### ISSUE THREAD

**Issue by rukala** [liqd/a4-meinberlin#356] opened 2017-05-12 10:18 UTC
After I uploaded a too big picture in the Bürgerhaushalt process on dev I got an Error 413 page instead of an error in the dashboard.
![bildschirmfoto 2017-05-12 um 12 18 09](https://cloud.githubusercontent.com/assets/11075214/25994164/153d70ce-370d-11e7-9720-e4007e42f97e.png)

**Comment by rukala** [comment] 2017-05-12 15:07
When I upload a picture a second time (after error in dashboard) and it has the same filename, it's not uploaded after pressing save.

**Comment by rukala** [comment] 2017-05-12 15:36
The same happens in all project-types. Also after navigating back from the error page and pressing save without selected image to upload, same error message occurs.

**Comment by 2e2a** [comment] 2017-05-24 12:14
This image size is limited by our web server to 10M. Is this not enough?

**Comment by xi** [comment] 2017-05-24 12:31
I think part of the issue is that the error page does not look particularly nice. I think it is an important security property that large file uploads are blocked before they even reach django. Still, it is not an ideal user experience.

Maybe we can have a compromise: Increase the maximum in nginx, so we can show nicer error pages for medium-large files. Huge files could still be blocked early.

**Comment by 2e2a** [comment] 2017-05-24 13:33
The current limit in django is 5M, in the webserver 10M.

Whereas we could increase the webserver limit, the disadvantage is that the image has to be fully uploaded before the django error is show. The webserver error is shown directly.

**Comment by 2e2a** [comment] 2017-06-16 07:48
@rukala Can we close this issue? Or should we change the limits?

**Comment by rittermo** [comment] 2017-10-12 14:02
I would like to re-open this issue. I think we need to increase the nginx filesize limit and then think about (i.e. write a US) how we could validate the filesize documents to be uploaded via JS, no?

**Comment by treba123** [comment] 2018-04-17 14:52
I just set the nginx filesize limit to 20mb on all a4 instances. I'm rather reluctant to increase it further as that opens the door for DDOS things/makes it easier.

File size check seems to easy, though, [here](https://www.sanwebe.com/2013/10/check-input-file-size-before-submit-file-api-jquery) is an example

**Closed** 2019-03-25 13:02 UTC
Labels: bug
