### ISSUE TITLE
Dashboard: Error 413 if file size is too large

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-meinberlin#894] opened 2017-10-12 12:57 UTC
When I create new project and try to upload an image as a header image in the dashboard that exceeds the file size limit, I get a 413 error page instead of a validation error in the form. I think we had that error in OPIN once and it had to do with the server settings for max upload file size.

Tested on meinberlin-dev on Safari 10.1

![bildschirmfoto 2017-10-12 um 14 54 09](https://user-images.githubusercontent.com/15341015/31496916-8bf922bc-af5d-11e7-8fe4-d70cc33c95aa.png)

The image fille size was 25,2 MB

**Comment by kleingeist** [comment] 2017-10-12 13:02
duplicate of #356 
the current filesize in nginx is set to 10MB. if a bigger image is uploaded it will be rejected by nginx and will never reach django.

**Closed by kleingeist** 2017-10-12 13:02 UTC
Labels: bug
