### ISSUE TITLE
#6669 Group member on project level: access to moderation and feedback-field

### ISSUE THREAD

**Issue by jostertag** [liqd/a4-meinberlin#4857] opened 2023-01-18 09:03 UTC
**URL:** e.g. https://meinberlin-dev.liqd.net/projekte/burgerhaushalt-3-phasen-mit-support-testprojekt/?mode=list
**user:** group member
**expected behaviour:** as a group member responsible for a project, I want to have the same rights as the initiator on the project level and therefore want to be able to give feedback to a proposal and edit the moderation-field.
**behaviour:** as a group member for the respective project I can delete/change a proposal, but cannot give feedback on the proposal. I can also don't see the moderation-field. Is 
**important screensize:** - 
**device & browser:** mac, ff
**Comment/Question:** 

Screenshot?

**Comment by fuzzylogic2000** [comment] 2023-01-18 12:44
duplicate of #4717

**Closed by fuzzylogic2000** 2023-01-18 12:44 UTC
