### ISSUE TITLE
unclear verification email wording 

### ISSUE THREAD

**Issue by goapunk** [liqd/a4-meinberlin#3530] opened 2021-04-01 12:28 UTC
While skimming through some mails I've seen at least two mails of users who instead of clicking the verification link in the email replied to it with text like "hereby I confirm my email address". Maybe it might make sense to add something like "[...] confirm by clicking the link below" to make it more clear that you are not supposed to reply to this mail. Not sure if it's really necessary since only very few struggled with this...

**Comment by CarolingerSeilchenspringer** [comment] 2021-06-24 06:51
@goapunk thanks for pointing that out. I would handle this as a story because it is not a bug and texts of all mails have been discussed with client. But as you said only very few struggle with this, I will close this issue and write a reminder-story that if we touch this mail again, we'll add a notice as you suggested.

**Closed by CarolingerSeilchenspringer** 2021-06-24 06:51 UTC
