### ISSUE TITLE
mB - not started module not shown when multimodule

### ISSUE THREAD

**Issue by Ronja-liqd** [liqd/a4-meinberlin#5140] opened 2023-06-22 11:48 UTC
**URL:** https://meinberlin-dev.liqd.net/projekte/module/burgerinnenhaushalt-1-phase-12/
**user:** all
**expected behaviour:** maps, polls etc of not started modules are shown.
**behaviour:** Nothing is shown when there are multiple modules.
**important screensize:**
**device & browser:** all
**Comment/Question:** 
Is this supposed to be like this / has it always been like this?

Screen
<img width="1431" alt="Bildschirm­foto 2023-06-19 um 10 12 28" src="https://github.com/liqd/a4-meinberlin/assets/113356258/d7ebab08-a441-4d12-a116-2f4b4428396b">
shot?

**Comment by Rineee** [comment] 2023-06-22 15:08
@Ronja-liqd I cannot reproduce this, for me it looks like this (I made one more module to start in fututre): 

![image](https://github.com/liqd/a4-meinberlin/assets/9589411/cff5d4ec-afb3-43bc-83dc-90d86b0adee5)

Can you check again maybe?

**Comment by CarolingerSeilchenspringer** [comment] 2023-06-23 10:14
@Rineee I talked with @Ronja-liqd about this and just labeled this issue as a question: In multimodule projects, have we never shown the map or poll or anything before the phase? e.g. a poll in single module project looks like this (screenshot). In a multimodule project the poll (or map etc.) is not shown, only module title and description. This is inconsistent, but if it is not a bug we will make a story out of this.
<img width="832" alt="Bildschirmfoto 2023-06-23 um 12 11 45" src="https://github.com/liqd/a4-meinberlin/assets/35491681/b66d3499-3b24-48de-8620-ed38192eb679">

**Comment by Rineee** [comment] 2023-06-23 10:56
@CarolingerSeilchenspringer @Ronja-liqd Ahh, now I get what you mean! To be honest, I dont know if has always been like that, but agree that it is inconsistent, so we should probably change it?

**Comment by CarolingerSeilchenspringer** [comment] 2023-06-23 14:33
@Rineee yes, I think we should be consistent here. How complex is it? Should we rather put that into a story?

**Comment by Rineee** [comment] 2023-06-26 08:47
Not sure about complexity, probably a small story would be good!

**Comment by CarolingerSeilchenspringer** [comment] 2023-06-26 10:41
@Rineee I made a story so will close this issue.

**Closed by CarolingerSeilchenspringer** 2023-06-26 10:41 UTC
Labels: Type: Question
