### ISSUE TITLE
secondary filter smartphone

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1964] opened 2019-02-07 15:38 UTC
if I cklick on the x to close the overlay of secondary filter, the blue filterbar is gray. If I open the filter again, the symbol next to organisation filter is missing.
Google Pixel 2 chrome

<img width="276" alt="bildschirmfoto 2019-02-07 um 16 35 50" src="https://user-images.githubusercontent.com/35491681/52422623-ad571e80-2af6-11e9-9423-21e92f5cbec3.png">
<img width="276" alt="bildschirmfoto 2019-02-07 um 16 36 00" src="https://user-images.githubusercontent.com/35491681/52422625-afb97880-2af6-11e9-95b1-58905d3f6100.png">

**Comment by phillimorland** [comment] 2019-02-11 13:15
tried with several variations but cannot reproduce on browserstack so closing

**Closed by phillimorland** 2019-02-11 13:15 UTC
Labels: frontend

**Comment by CarolingerSeilchenspringer** [comment] 2019-02-11 13:26
@phillimorland I tried again and it is fine now. I guess it changed with some other changes. Or the filter had a bad day ;-)
