### ISSUE TITLE
#6536 breaking points 

### ISSUE THREAD

**Issue by SandisStudi** [liqd/a4-meinberlin#4656] opened 2022-11-07 16:24 UTC
**URL:** https://meinberlin-dev.liqd.net/projekte/module/priorisierung-2/?ordering=name&category=363&labels=202
or 
https://meinberlin-dev.liqd.net/projekte/module/brainstorming-2/?ordering=-created&labels=185&category=349
**user:** anonym, reg. user, admin
**expected behaviour:** when looking at the top line of proposal list, i want so see "Merkmale" "Kategorie" and "Sortieren:.." tiles in one line or stacked
**behaviour:** if the "Merkmale" and "Kategorie" - tiles gets to big, the "Sortieren:.." tile is shown in the next line on the right side
**important screensize:** 801 - 900 ppx and 910 - 1920 ppx
**device & browser:** Mac + Windows (Edge,Chrome,Firefox) and Ipad Pro
**Comment/Question:** 

Screenshot?
<img width="904" alt="grafik" src="https://user-images.githubusercontent.com/113611764/200361736-700b883b-8e0c-4453-af5b-58821914cea9.png">

**Comment by CarolingerSeilchenspringer** [comment] 2022-11-08 12:01
does this need another story or do we find an easy fix like having sorting on the left side for smaller screens? @mcastro-lqd what should we do here?

**Comment by mcastro-lqd** [comment] 2022-11-08 13:32
Hey @CarolingerSeilchenspringer and @SandisStudi, thanks for noticing that. Since we are adding more and more filter options that's why I decided to hide all the filters under the filter button, and they should all show up aligned to the left below the search + sort + filter section. 
<img width="613" alt="Screenshot 2022-11-08 at 14 29 53" src="https://user-images.githubusercontent.com/59610786/200577387-15c6bee9-d924-41d8-bdd0-4dbace80adb0.png">

**Comment by CarolingerSeilchenspringer** [comment] 2022-11-08 14:11
@mcastro-lqd but implementing the filter hide function for django lists would be a story. In the django lists we don't have all the filters that the react lists have.  So the issue is only for idea collection, brainstorming, Kiezkasse and priorisation and only if they use both category and filter. And it is only between 992 and 1104 px. I would think that it does not have an impact on too many users. So I would rather close this issue and wait for us to write the other lists in django. Please reopen @mcastro-lqd or @phillimorland if you think that we should fix this sooner.

**Closed by CarolingerSeilchenspringer** 2022-11-08 14:11 UTC
Labels: Type: UX/UI or design, Prio: Medium
