### ISSUE TITLE
/projekte broken on safari

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#5000] opened 2023-02-27 09:43 UTC
**URL:** https://meinberlin-dev.liqd.net/projekte/
**user:** any
**expected behaviour:** 
**behaviour:** cannot see list, map and filter (only header/footer)
**important screensize:**
**device & browser:** safair on mac
**Comment/Question:** 

Screenshot?
<img width="1134" alt="Bildschirmfoto 2023-02-27 um 10 39 50" src="https://user-images.githubusercontent.com/35491681/221528578-723b1c6b-cd06-4ff3-b3b6-8862809784bc.png">

**Comment by philli-m** [comment] 2023-02-27 11:19
@CarolingerSeilchenspringer cannot reproduce, can you include versions of mac OS and safari

**Comment by goapunk** [comment] 2023-03-02 08:22
fixed by #5007

**Closed by goapunk** 2023-03-02 08:22 UTC
Labels: Type: Bug, Prio: Medium
