### ISSUE TITLE
React success message disappears only after reload

### ISSUE THREAD

**Issue by 2e2a** [liqd/a4-meinberlin#754] opened 2017-08-30 13:28 UTC
When a document or poll is saved the shown success message does not disappear on further react actions (e.g. adding a paragraph). It stays until a page reload.

This might be confusing for the user.

**Comment by vellip** [comment] 2017-09-04 06:44
This should be working as intended, the user can close it manually or when something's entered into a field.

**Comment by 2e2a** [comment] 2017-09-04 09:39
> This should be working as intended, the user can close it manually or when something's entered into a field.

This does not apply to the ck editor. So editing something there does not close the success message. Not sure if this is worth fixing, though.

**Closed** 2017-09-27 12:03 UTC
Labels: bug
