### ISSUE TITLE
dev/dashboard: area settings for modules with map broken

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3654] opened 2021-06-22 11:14 UTC
**URL:** https://meinberlin-dev.liqd.net/dashboard/modules/burgerinnenhaushalt-2-phasen-3/area_settings/
**user:** initiator
**expected behaviour:** can set area/map for my map module
**behaviour:** cannot chose district nor draw or upload a polygon.
**important screensize:**
**device & browser:** tested on mac big sur on both chrome and firefox
**Comment/Question:** nearly same issue (also two dropdowns, but only one works) #3655
![Bildschirmfoto 2021-06-22 um 13 09 06](https://user-images.githubusercontent.com/35491681/122914996-8d3cf880-d35b-11eb-920d-1411621ef188.png)

**Comment by fuzzylogic2000** [comment] 2021-06-22 11:35
Oh, looks like one and a half dropown. 
The link gets me to a 404, though. @CarolingerSeilchenspringer Could you update it? Thanks!

**Comment by CarolingerSeilchenspringer** [comment] 2021-06-22 13:54
@fuzzylogic2000 updated the URL

**Comment by CarolingerSeilchenspringer** [comment] 2021-06-22 13:57
I think it is a dropdown issue, the "account-dropdown" also doesn't work. The dropdown to connect projects to plans works though, but I think it is a different type of dropdown?

**Comment by fuzzylogic2000** [comment] 2021-06-22 14:14
> I think it is a dropdown issue, the "account-dropdown" also doesn't work. The dropdown to connect projects to plans works though, but I think it is a different type of dropdown?

Yes, you're right! So, it's one issue! Well, at least this one and #3655. The pin-thing is a bit different, I think. Will merge these two!

**Comment by fuzzylogic2000** [comment] 2021-06-22 14:17
On the other hand, it has to be fixed somewhere else (even when it's the same thing to do to fix it). Will just leave both open...

**Comment by goapunk** [comment] 2021-06-24 07:22
I think I found the cause for this and #3655: the select2 initialization is called twice because we include `adhocracy4.js` in the extra_js block in `nav_modules.html` now for the new blueprint modal to work. Not sure how to fix this without breaking the modal though, so I might leave the fixing to someone more knowledgeable.

**Comment by phillimorland** [comment] 2021-06-24 09:16
We may not need the select2 anymore as bootstraps current select is pretty good and any reduced load would be a plus, I also found a stripped down version of it in a4 that I'm not sure where it should be used?! will keep looking into it

**Comment by phillimorland** [comment] 2021-06-24 09:34
@CarolingerSeilchenspringer what is the 'account dropdown'?

**Comment by CarolingerSeilchenspringer** [comment] 2021-06-24 10:13
@phillimorland with "account dropdown" I mean the one on the upper right corner with the user name on it. Do you have a better name?

**Comment by phillimorland** [comment] 2021-06-24 10:24
@CarolingerSeilchenspringer ahhh ok, that was my first thought but it's working on my laptop, hence confusion. Can you add an issue with browser and screen sizes and i'll look into it? might be a mac thing. Other stuff should be fixed with the next merge, sorry should have warned you before I left that I did a bootstrap update, I was expecting some problems but forgot to mention it.

**Comment by Rineee** [comment] 2021-06-24 10:57
@phillimorland I think it was only not working inside the dashboard.. but maybe it will be fixed with your PR? Lets see!

**Comment by CarolingerSeilchenspringer** [comment] 2021-06-24 11:24
@phillimorland I added a new issue for the dropdown upper right corner: https://github.com/liqd/a4-meinberlin/issues/3661

**Closed** 2021-06-24 12:17 UTC
Labels: Prio: Medium, Type: Bug
